monitorrule=make:Dell Inc.,model:DELL AW2518HF,width:1920,height:1080,refresh:239.76,x:0,y:0,scale:1,vrr:0
monitorrule=make:LG Electronics,model:LG ULTRAGEAR+,width:2560,height:1440,refresh:239.970,x:0,y:0,scale:1,vrr:0

